### PR TITLE
Add minimal sphinx doc available via Readthedocs

### LINKED ISSUE #126: Readthedocs diffsims API documentation?
kikuchipy now depends on diffsims for electron scattering and diffraction (namely the `crystallography.ReciprocalLatticePoint` class): https://github.com/pyxem/kikuchipy/pull/220. I would therefore want the diffsims API to be easily browsable like kikuchipy's (https://kikuchipy.org/en/latest/reference.html) or orix' (https://orix.readthedocs.io/en/stable/reference.html).

The intersphinx functionality (click e.g. on the `Rotation` link in the "Parameters" docstring here: https://kikuchipy.org/en/latest/reference.html#kikuchipy.generators.EBSDSimulationGenerator) is also very nice, which becomes more important as kikuchipy depends more and more on orix (and hopefully diffsims).

I volunteer to set up a simple Readthedocs documentation available via https://diffsims.rtfd.io, as I did for orix.

### PR DESCRIPTION
**Pull request by hakonanes**
Signed-off-by: Håkon Wiik Ånes <hwaanes@gmail.com>

---
name: Add minimal sphinx doc available via Readthedocs
about: Add minimal sphinx doc available via Readthedocs

---

**Release Notes**
> developer change
Add minimal sphinx doc available via Readthedocs

**What does this PR do? Please describe and/or link to an open issue.**
Add minimal sphinx doc available via Readthedocs https://diffsims.readthedocs.io or https://diffsims.rtfd.io.

Two pages are available:
* Index (front) page similar to orix' page but without the "Work using diffsims" part.
* Full API reference.

Added package collections named "doc", "tests" and "dev" (both doc, tests + black/pre-commit) in `extras_require` to setup.py. These package collections can be installed, in addition to regular dependencies, like `pip install diffsims[doc]` or `pip install -e .[doc]` and similar. I can remove or change these if black and pre-commit or whatever are unwanted.

Closes #126.

**Are there any known issues? Do you need help?**
1. Don't know how well the ReStructuredText formatting in docstrings and comments are... This might need some changes.
2. Haven't looked at what should be available via the API reference and what should be private. Don't know if underscores are used everywhere where a class/method/function should be private?

**Work in progress?**
- [x] Push this branch to the main/upstream repo so that the documentation can be built by Readthedocs and viewed by anyone interested via the above links *before* this PR is merged. (Will use [skip ci] to go easy on Travis.)
- [x] Finish API reference page.
- [x] Fix (potential) bad ReStructuredText formatting.
- [x] Add docs badge to README.

### CODE REVIEW

**Comment by hakonanes** [comment]
@pc494 added you as an admin on readthedocs like on orix.

**Comment by hakonanes** [comment]
I'm working to finish this now.

Question: what is the idea behind the imports in `diffsims/__init__.py`? Is new functionality added to this import structure as it is added to the package? If not, should we go for something like is in orix, where no modules are importable from `orix/__init__.py`, only via `orix.vector` etc.?

**Comment by hakonanes** [comment]
The orix import structure was discussed briefly here: https://github.com/pyxem/orix/issues/113

**Comment by hakonanes** [comment]
The thing is that generating an API reference with Sphinx is much easier if there is a nice import structure in the `__init__.py` files.

An example illustrating my above question: should `diffsims.generators.rotation_list_generator.get_fundamental_zone_grid()` be imported like

```python
>>> from diffsims.generators.rotation_list_generator import get_fundamental_zone_grid
>>> out = get_fundamental_zone_grid()
```

or like

```python
>>> from diffsims.generators import get_fundamental_zone_grid
>>> out = fundamental_zone_grid()
```

For the latter we need to add

```python
from diffsims.generators.rotation_list_generator import get_fundamental_zone_grid
```

in `diffsims/generators/__init__.py`.

Edit: I think the latter is best, having to import `get_fundamental_zone_grid` from the `rotation_list_generator` module.

**Comment by hakonanes** [comment]
I'm happy with this now: https://diffsims.readthedocs.io/en/api-via-readthedocs/index.html.

Although lots of the docstrings in all modules but `crystallography` and `structure_factor` needs updates. I've touched up those that gave warnings when building the docs.

**Review by dnjohnstone — APPROVED** [review]

**Comment by dnjohnstone** [comment]
Will merge assuming tests pass

**Comment by hakonanes** [comment]
Will add changelog first

**Comment by hakonanes** [comment]
... Did not know that [skip ci] cancels the ongoing build.

**Comment by hakonanes** [comment]
No, it doesn't, it just hides it here.

**Comment by hakonanes** [comment]
All tests pass: https://travis-ci.org/github/pyxem/diffsims

**Comment by pc494** [comment]
> The thing is that generating an API reference with Sphinx is much easier if there is a nice import structure in the `__init__.py` files.
> 
> An example illustrating my above question: should `diffsims.generators.rotation_list_generator.get_fundamental_zone_grid()` be imported like
> 
> ```python
> >>> from diffsims.generators.rotation_list_generator import get_fundamental_zone_grid
> >>> out = get_fundamental_zone_grid()
> ```
> 
> or like
> 
> ```python
> >>> from diffsims.generators import get_fundamental_zone_grid
> >>> out = fundamental_zone_grid()
> ```
> 
> For the latter we need to add
> 
> ```python
> from diffsims.generators.rotation_list_generator import get_fundamental_zone_grid
> ```
> 
> in `diffsims/generators/__init__.py`.
> 
> Edit: I think the latter is best, having to import `get_fundamental_zone_grid` from the `rotation_list_generator` module.

Your edit is slightly confusing here because you say "latter" but then spell out the "former" route. For diffsims at the moment I prefer:

`from diffsims.generators.rotation_list_generator import get_fundamental_zone_grid`

**Comment by pc494** [comment]
> I'm working to finish this now.
> 
> Question: what is the idea behind the imports in `diffsims/__init__.py`? Is new functionality added to this import structure as it is added to the package? If not, should we go for something like is in orix, where no modules are importable from `orix/__init__.py`, only via `orix.vector` etc.?

I think this could and probably should be changed to follow the style in orix.

**Comment by hakonanes** [comment]
> > I'm working to finish this now.
> > Question: what is the idea behind the imports in `diffsims/__init__.py`? Is new functionality added to this import structure as it is added to the package? If not, should we go for something like is in orix, where no modules are importable from `orix/__init__.py`, only via `orix.vector` etc.?
> 
> I think this could and probably should be changed to follow the style in orix.

Okay. I could make a PR right away, but changing how modules should be imported might affect how they are imported in pyxem. So, I'll set this up as it is in orix, create a conda env with pyxem, but import diffsims from that PR, then run the pyxem tests and see if any fail.

Edit: Yes, you're right in that I ment the FORMER.

**Pull request merged**
