### PR TITLE
added pattern-to-mask feature

### PR DESCRIPTION
**Pull request by din14970**
---
name: Template to binary mask
about: Implemented a small feature whereby a template can be converted to corresponding binary mask of circles.

---

**Release Notes**
* Added a method `get_as_mask` in `DiffractionSimulation` with a number of options
* Added a module `mask_utils` under utils. 

**What does this PR do? Please describe and/or link to an open issue.**
For my work I would like to easily generate masks from templates to perform multi-stage indexations. I always implemented this in hacky ways but decided it would be handy if `DiffractionSimulation` would have a method that converts it to a binary mask, similar as it can be converted to an image of Gaussians.

A simple example:
```python
import diffpy
from diffsims.generators.diffraction_generator import DiffractionGenerator

aus = diffpy.structure.loadStructure("austeniteLP.cif")
diff_gen = DiffractionGenerator(accelerating_voltage=200, shape_factor_model="lorentzian")

orientation = [0, 20, 45]
simulation = diff_gen.calculate_ed_data(aus,
                                        2.3,
                                        orientation,
                                        with_direct_beam=False,
                                        max_excitation_error=1e-1,
                                        )
simulation.calibration = 0.012

mask = simulation.get_as_mask((256, 256), radius = 10)
```
Plotting the simulated coordinates produces:
afbeelding

The image of the mask: 
afbeelding

One can specify whether one wants a "negative" or a "positive" mask. The radii of the circles can also be controlled - each can be set individually by passing an array into `radius` or the radius can be determined based on a function of the intensity, which can be passed in as `radius_function`.

Modifications can be made to the mask using additional functions in `mask_utils`. I added support for drawing a circle, any polygon, and an annulus. The functions work in-place, e.g.

```python
from pyxem.utils import mask_utils as mu
mask = mu.create_mask((512, 512))
mu.add_annulus_to_mask(150, 250, mask)
mu.add_circle_to_mask(256, 50, 30, mask, fill=True)
coords = np.array([[200, 200],
                   [350, 100],
                   [250, 350]])
mu.add_polygon_to_mask(coords, mask)
```
This produces a mask:
afbeelding

Maybe I didn't search hard enough, but I couldn't find these convenience functions to generate a mask in other packages.

**Describe alternatives you've considered**
I'm unsure whether the `mask_utils` fit all that well in diffsims and they would probably fit better in pyxem. On the other hand, I like that `get_as_mask` function being under `DiffractionSimulation`.

**Are there any known issues? Do you need help?**
I would say it's fully functional but a discussion may be needed on where to best place things. Also unit tests are still needed.

A lazy implementation using e.g. dask.futures or dask.delayed might be handy to generate a 4D-STEM sized mask without having it in memory. 

**Work in progress?**
If you know there is more to do, make a checklist here:
- [x] Unit testing
- [ ] Find a good place for mask functions

#### For reviewers

- [x] Check that the PR title is short, concise, and will make sense 1 year
  later.
- [x] Check that new functions are imported in corresponding `__init__.py`.
- [ ] Check that new features, API changes, and deprecations are mentioned in
      the unreleased section in `CHANGELOG.md`.

### CODE REVIEW

**Comment by hakonanes** [comment]
Without looking at the code, I quite like the masking utilities you're showing, and the functionality your describing. I would like something similar for extracting Kikuchi band intensities from positions of geometrical EBSD simulations in kikuchipy, and it looks like this is a perfect platform to build that from. I strongly suggest this be placed in diffsims and not in pyxem.

I'll leave it for someone else to review it, as I haven't used that part of the code.

**Comment by din14970** [comment]
@hakonanes I suppose this could be added as a utility function like `mask_band(xy, in-plane_angle, width)`. Shouldn't be too complicated.

**Comment by din14970** [comment]
A band feature on the mask is also possible now:

image

I'll just create some tests for these things

**Comment by din14970** [comment]
@pc494 I would say this is ready for review

**Review by pc494 — CHANGES_REQUESTED** [review]
This basically looks good to me apart from one thing.

It seems you are fixing masks inplace (which is fine), could you make this explicit in the various bits of docstrings:

eg: 
```
Returns
----------
mask : etc.
```

or 
```
Returns
----------
None : 
     mask is adjusted inplace
```

**Comment by hakonanes** [comment]
> It seems you are fixing masks inplace (which is fine), could you make this explicit in the various bits of docstrings:

If operations are done inplace I *always* state this in the top docstring description, e.g. ["Remove the static background in an EBSD scan inplace"](https://kikuchipy.org/en/latest/reference.html#kikuchipy.signals.EBSD.remove_static_background).

**Comment by pc494** [comment]
@din14970 if you are happy to deal with:
`Check that new functions are imported in corresponding __init__.py.`

I'll sort out the CHANGELOG, as it's got some conflicts at the moment after the patch release came out

**Comment by din14970** [comment]
@pc494  Hope that this is acceptable. Sorry for my ignorance but could you explain what the purpose of adding it to the `__init__` file is? Just so that all the functions are directly available under the `utils` namespace or?

**Comment by hakonanes** [comment]
> @pc494 Hope that this is acceptable. Sorry for my ignorance but could you explain what the purpose of adding it to the `__init__` file is? Just so that all the functions are directly available under the `utils` namespace or?

I think a clean import structure is *very* important. Ideally, everything should be available via a `diffsims.module.Class` or `diffsims.module.function`. To get this, we need to make stuff easily available via `module/__init__.py`.

For orix e.g, we can do `from orix.vector import Vector3d`, instead of `from orix.vector.vector3d import Vector3d`, since `from orix.vector.vector3d import Vector3d` is placed in `vector/__init__.py`.

A final comment on this: we should add a todo-point in the PR template to ensure that we also add new functionality in the API reference documentation (doc/reference.rst). Will have a look at this in a later PR.

**Comment by hakonanes** [comment]
Just to clarify: I think a clean and understandable import structure documented in the [API reference](https://diffsims.readthedocs.io/en/latest/reference.html) makes it easy for the user to quickly navigate the package, without having to rely on a user guide/notebook.

**Comment by din14970** [comment]
@hakonanes @pc494 ok, thanks for the clarification! One thing to keep in mind then is that we don't duplicate names in different modules. Will take care about changelog and init next time. Hope these mask tools end up being useful, I often find creating a custom mask a quite annoying task.

**Comment by hakonanes** [comment]
> One thing to keep in mind then is that we don't duplicate names in different modules

Good point, a clear and easily available import structure should reduce the chances of doing this!

**Pull request merged**
