### PR TITLE
Update docs: PyData sphinx theme, simplify autogen of API

### PR DESCRIPTION
**Pull request by hakonanes**
#### Description of the change
* Change docs theme from Furo to PyData's theme, in line with kikuchipy, orix and HyperSpy (soon pyxem as well)
* Simplify autogeneration of API by listing all public facing functionality in module's `__all__` lists. We can thus remove the hard-coded list in `reference.rst`. The new lists define public functionality.
* Add dev dependency on `sphinx_design` for nice cards and tabs on the landing page
* Use pyxem logo until a new one is made

#### Progress of the PR
- [n/a] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [x] Unit tests with pytest for all lines
- [x] Clean code style by [running black](https://diffsims.readthedocs.io/en/latest/contributing.html#get-the-style-right)

#### For reviewers

- [ ] The PR title is short, concise, and will make sense 1 year later.
- [ ] New functions are imported in corresponding `__init__.py`.
- [ ] New features, API changes, and deprecations are mentioned in the
      unreleased section in `CHANGELOG.rst`.
- [ ] Contributor(s) are listed correctly in `credits` in `diffsims/release_info.py` and
      in `.zenodo.json`.

### CODE REVIEW

**Comment by hakonanes** [comment]
Let's merge #194 and release v0.5.2 before merging this.

**Comment by hakonanes** [comment]
@pc494 and @CSSFrancis, could one of you review this PR? There aren't any breaking changes as I'm aware of.

**Comment by CSSFrancis** [comment]
> @pc494 and @CSSFrancis, could one of you review this PR? There aren't any breaking changes as I'm aware of.

I'll try to get to this later today unless @pc494 beats me to it!

**Review by CSSFrancis — APPROVED** [review]
This looks good to me.  @hakonanes this seems pretty straight forward you can merge this if you would like!  I checked out the documentation too and it looks good!

**Comment by hakonanes** [comment]
Thanks for having a look!

**Pull request merged**
