### PR TITLE
Prepare for release

### PR DESCRIPTION
**Pull request by CSSFrancis**
- [x] Update the version number in release_info.py.
- [x] Update the CHANGELOG.rst file with the date and new version number and a description of the changes.
- [ ] Update the list of contributors in both the release_info.py and .zenodo.json files. __ Make sure that the Zenodo file is valid JSON __.
- [ ] Commit the changes and push them to the repository.
- [ ] Create a new tag with the “v” + version number (e.g. “v0.16.0”) and make a new release on GitHub.
- [ ] Wait for the CI server to finish the release proces

### CODE REVIEW

**Comment by CSSFrancis** [comment]
This should get us compatible with numpy 2.0.0.  @hakonanes Let me know if there is anything else to be done otherwise I will make the release.

**Review by hakonanes — APPROVED** [review]
Looks good, go ahead and merge!

**Comment by hakonanes** [comment]
Regarding your points in the top comment:
* List of contributors: should be the same as for the previous release, v0.6.0
* The tag is created from an annotated release. Can you make one in the similar vein as before?

**Comment by CSSFrancis** [comment]
> * The tag is created from an annotated release. Can you make one in the similar vein as before?

@hakonanes I just have to make a release with a new v0.6.1 tag correct.  You have me second guessing myself  :)

**Comment by hakonanes** [comment]
Sorry about that! I read your comment as suggesting to create one locally and push it, which we don't do.

**Pull request merged**
