### PR TITLE
Fixed a number of typos in elements

### LINKED ISSUE #91: Typo in ATOMIC_SCATTERING_PARAMS_PENG
**Describe the bug**
In [here](https://github.com/pyxem/diffsims/blob/11c75ba262525d080e6a64c90812ce17077559b6/diffsims/utils/atomic_diffraction_generator_support/discretise_utils.py#L1030) 

there is a typo: Al is typed as A1. Passing a structure with Al in it results in `ValueError: Atom Z='Al' is not supported`

### PR DESCRIPTION
**Pull request by M0hsend**
---
Fixing some typos in the elements symbols
about: A couple of elements were misspelt in the atomic scattering list (See issue here #91). These have been fixed here.

---

### CODE REVIEW

**Comment by dnjohnstone** [comment]
Thanks @M0hsend - this looks good, but the tests were consistent with the old (wrong) list so we need to update those also, Travis is highlighting which ones in particular. Would you be able to do that?

**Comment by M0hsend** [comment]
Sorry @dnjohnstone did not realize this. Will fix shortly.

**Comment by M0hsend** [comment]
It is now giving an error just for the macOS build. Not sure how to fix, could you take a quick look? @dnjohnstone

**Comment by pc494** [comment]
Looks unrelated to me, will try and coerce Travis into building correctly.

**Pull request merged**
