### PR TITLE
Starting 0.2.0 rc.1 (Supersedes #29)

### PR DESCRIPTION
**Pull request by pc494**
---

name: Starting 0.2.0 rc.1 (Supersedes #29)
about: As previous, with details to follow.

---

**Release Notes**
> major 
> improvement & bugfix & developer change

**Work in progress?**
(more to be added)
- [ ] ~Kirkland Scattering~ (move to an issue, and do in a separate PR)
- [ ] PR template
- [ ] debeye waller docstring is slightly wrong (should be `dict {str:float} or float`)

### CODE REVIEW

**Comment by dnjohnstone** [comment]
I think we need to address #11 in this one to sort saving/loading of libraries etc.

Probably using an hdf5 format is the best route - @stefsmeets I know we discussed this in the past, do you have any opinions / suggestions for this?

**Comment by stefsmeets** [comment]
> Probably using an hdf5 format is the best route - @stefsmeets I know we discussed this in the past, do you have any opinions / suggestions for this?

I agree hdf5 would be most flexible. I tried pickling (also using `dill`), but it crashed out on me. But I'm worried that hdf5 will be difficult to maintain, because a lot of custom attributes are being stored on different objects (also on `pyxem`). Hyperspy's `BaseSignal` already has a `.save` method, can we not make use of that somehow?

**Comment by dnjohnstone** [comment]
Yeah, in pyxem we intend to mostly use the hyperspy.save / load method that already exists.

In the case of simulated libraries though, these things are generated by diffsims, which we're trying to keep a lighter dependency list for. i.e. it does not depend on hyperspy and so we're going to have to do something different...

**Comment by dnjohnstone** [comment]
Is this PR dead @pc494 ?

**Comment by pc494** [comment]
Yep, I'll pull out the useful stuff somewhere else.

**Pull request closed without merging**
